# Generated by Django 3.2.13 on 2022-06-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geeks_field', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='year_in_school',
            field=models.CharField(choices=[('School_student', (('FR', 'Fresher'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate'))), ('clg_student', (('FR', 'Fresher'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')))], default='FR', max_length=2),
        ),
    ]
