# Generated by Django 3.2.13 on 2022-06-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_auto_20220616_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='geeks_field',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
