# Generated by Django 3.2.13 on 2022-06-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_alter_vehicle_geeks_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='geeks_field',
            field=models.CharField(blank=True, db_column='col_1', default='GfG is bets', max_length=200, null=True),
        ),
    ]
