# Generated by Django 3.2.13 on 2022-06-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_alter_vehicle_geeks_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='geeks_field',
            field=models.CharField(blank=True, db_column='col_1', default='GfG is bets', help_text='Please use the following format: <em>YYYY-MM-DD</em>.', max_length=200, null=True),
        ),
    ]
