# Generated by Django 3.2.13 on 2022-06-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0008_alter_vehicle_geeks_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='hello',
            fields=[
                ('x_field', models.IntegerField(default='hello....', primary_key=True, serialize=False)),
            ],
        ),
    ]
