# Generated by Django 3.2.13 on 2022-06-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0009_hello'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hello',
            name='x_field',
            field=models.IntegerField(default='hello....', editable=False, primary_key=True, serialize=False),
        ),
    ]
