# Generated by Django 3.2.13 on 2022-06-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0010_alter_hello_x_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('z_field', models.CharField(error_messages={'unique': 'please enter correct data'}, max_length=200, unique=True)),
            ],
        ),
    ]
