# Generated by Django 3.2.13 on 2022-06-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0011_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='z_field',
            field=models.CharField(error_messages={'unique': 'please enter correct data'}, max_length=200, unique=True, verbose_name='geeks_new_name'),
        ),
    ]
