# Generated by Django 3.2.13 on 2022-06-17 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0013_validation_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply_field',
            fields=[
                ('type_field', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='hello',
            name='x_field',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
