# Generated by Django 3.2.13 on 2022-06-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0014_auto_20220617_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply_field',
            name='type_field',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='new_name_field'),
        ),
    ]
