# Generated by Django 3.2.13 on 2022-06-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0018_auto_20220620_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person_DoB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('L_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
            ],
        ),
    ]
