# Generated by Django 3.2.13 on 2022-06-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0021_students_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='st_name',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
