# Generated by Django 3.2.13 on 2022-06-20 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0022_students_st_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Student_abs',
        ),
    ]
