# Generated by Django 3.2.13 on 2022-06-21 07:47

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0024_auto_20220621_1227'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='student_abs',
            managers=[
                ('new_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
