# Generated by Django 3.2.13 on 2022-06-21 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='st_rollno',
        ),
        migrations.AddField(
            model_name='school',
            name='prcpl_name',
            field=models.CharField(default='xyz', max_length=70),
        ),
        migrations.AddField(
            model_name='student',
            name='sch_name',
            field=models.OneToOneField(blank=True, max_length=70, null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.school'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='sch_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.school'),
        ),
    ]
