# Generated by Django 3.2.13 on 2022-06-22 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20220621_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sch_name',
            field=models.ForeignKey(blank=True, max_length=70, null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.school'),
        ),
    ]
