# Generated by Django 3.2.13 on 2022-06-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_alter_student_sch_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='tec_name',
        ),
        migrations.AddField(
            model_name='books',
            name='tec_name',
            field=models.ManyToManyField(to='demo.Teacher'),
        ),
    ]
