# Generated by Django 3.2.13 on 2022-06-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_auto_20220622_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='b_name',
            field=models.ManyToManyField(max_length=70, to='demo.Books'),
        ),
        migrations.AddField(
            model_name='section',
            name='tec_name',
            field=models.CharField(default='xyz', max_length=70),
        ),
        migrations.AlterField(
            model_name='section',
            name='sec_name',
            field=models.CharField(max_length=70),
        ),
    ]
