# Generated by Django 3.2.13 on 2022-06-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_auto_20220622_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='tec_name',
            new_name='class_tech_name',
        ),
        migrations.AddField(
            model_name='section',
            name='lecture_techer_name',
            field=models.CharField(default='xyz', max_length=70),
        ),
    ]
