# Generated by Django 3.2.13 on 2022-06-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0008_alter_teacher_sub_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='sub_name',
            field=models.ManyToManyField(to='demo.Books'),
        ),
    ]
