# Generated by Django 3.2.13 on 2022-06-28 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fb_apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='follow_user_id',
        ),
        migrations.AddField(
            model_name='followers',
            name='follow_user_id',
            field=models.ForeignKey(default='xyz', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='following',
            name='following_user_name',
        ),
        migrations.AddField(
            model_name='following',
            name='following_user_name',
            field=models.ForeignKey(default='xyz', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
