# Generated by Django 3.2.13 on 2022-06-28 13:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fb_apps', '0002_auto_20220628_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='follow_user_id',
        ),
        migrations.AddField(
            model_name='followers',
            name='follow_user_id',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='following',
            name='following_user_name',
        ),
        migrations.AddField(
            model_name='following',
            name='following_user_name',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
