# Generated by Django 3.2.13 on 2022-06-29 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb_apps', '0006_auto_20220629_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfollowing',
            name='following_user_name',
        ),
        migrations.RemoveField(
            model_name='userfollowing',
            name='usr_follwing',
        ),
        migrations.DeleteModel(
            name='UserFollowers',
        ),
        migrations.DeleteModel(
            name='UserFollowing',
        ),
    ]
