# Generated by Django 3.2.13 on 2022-07-13 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='emp_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='cmp_name',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='interview_app.company'),
        ),
    ]
